// Get Product List
export const GET_ALL_PRODUCTS = "GET_PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

// Get Individual Product
export const GET_PRODUCT = "GET_PRODUCT_DATA";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_DATA_FAILURE";
